In [132]:
import numpy as np
arr = np.array ([10,20,30,40,50])
print (arr)
print (type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


### Documentation
https://numpy.org/doc/stable/

In [133]:
# Create a 0D Array
arr0 = np.array(24)
print ('0D array is', arr0)
# Create a 1D Array
arr1 = np.array([1,2,3,4])
print ('1D array is', arr1)
# Create a 2D Array
arr2 = np.array([[1,1,1],[1,2,1]])
print ('2D array is', arr2)
# Create a 3D Array
arr3 = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
print ('3D array is', arr3)

0D array is 24
1D array is [1 2 3 4]
2D array is [[1 1 1]
 [1 2 1]]
3D array is [[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]


In [134]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [135]:
e = np.arange(0, 10, 2)
print(e)

[0 2 4 6 8]


In [136]:
f = np.linspace(0, 1, 5)
print(f)

[0.   0.25 0.5  0.75 1.  ]


In [137]:
g = np.eye(3)
print(g)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [138]:
d = np.full((3,3),8)
print(d)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [139]:
b = np.zeros((4,5))
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [140]:
x = np.arange(0,100)
print(x)
print(x[3])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
3


In [141]:
x[3]

np.int64(3)

In [142]:
x[2:6]

array([2, 3, 4, 5])

In [143]:
x[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [144]:
x[::3]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [145]:
x[2::]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [146]:
x[x%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [147]:
x[0::3]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [148]:
x[0:80:3]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78])

In [149]:
h = np.arange(5, 15, 2)
print(h)

[ 5  7  9 11 13]


In [150]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1,2])

6


In [151]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [159]:
import random
np.random.rand()

0.33086553681413544