In [1]:
import numpy as np

In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [59]:
newarr_1 = arr.reshape(2, 6)
print(newarr_1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [7]:
arr3d = np.array([[[1,2,3], [4,5,6], [7,8,9], [10,11,12]]])
print(arr3d)
print(arr3d.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
(1, 4, 3)


In [9]:
arr3d.ndim

3

In [4]:
flattened_array = arr3d.flatten()
print(flattened_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d.shape)
print(arr2d)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [10]:
arr2d.ndim

2

In [11]:
transposed_array2d = arr2d.transpose()
print(transposed_array2d)

[[1 4]
 [2 5]
 [3 6]]


In [14]:
print(transposed_array2d.shape)

(3, 2)


In [12]:
transposed_array3d = arr3d.transpose()
print(transposed_array3d)

[[[ 1]
  [ 4]
  [ 7]
  [10]]

 [[ 2]
  [ 5]
  [ 8]
  [11]]

 [[ 3]
  [ 6]
  [ 9]
  [12]]]


In [15]:
print(transposed_array3d.shape)

(3, 4, 1)


In [17]:
a = np.array([30, 20, 10])
a.ndim
b = np.array([10, 20, 30])

In [22]:
result = np.add(a,b)
print(f"Element wise addition of two array using np.add is: {result}")

Element wise addition of two array using np.add is: [40 40 40]


In [26]:
c = np.array([[30, 20, 10], [50, 60, 70]])
c.ndim
d = np.array([[10, 20, 30], [40, 30, 80]])
result = np.subtract(c, d)
print(f"Element wise subtraction of two array using np.subtract is: {result}")

Element wise subtraction of two array using np.subtract is: [[ 20   0 -20]
 [ 10  30 -10]]


In [27]:
a = np.array([30, 20, 10])
b = np.array([10, 20, 30])
result = np.multiply(a, b)
print(f"Element wise multpilication of two array using np.multiply is: {result}")

Element wise multpilication of two array using np.multiply is: [300 400 300]


In [39]:
a = np.array([[1, 2, 1], [2, 2, 3]])
b = np.array([3, 4, 5])
#b1 = np.array([3, 4])
#result_error = np.divide(a, b1) # ValueError: operands could not be broadcast together with shapes (2,3) (2,) 
#print(result_error)
print(a/2)
result = np.divide(a, b)
print(result)

[[0.5 1.  0.5]
 [1.  1.  1.5]]
[[0.33333333 0.5        0.2       ]
 [0.66666667 0.5        0.6       ]]


In [38]:
a = np.array([2, 2, 2, 2, 2])
b = np.array([2, 3, 4, 5, 6])

c = np.power(a,b)
print(c)

[ 4  8 16 32 64]


In [40]:
a = 2 * np.ones((1, 5), dtype=int)
print(a)

[[2 2 2 2 2]]


In [43]:
array = np.array([[4, 3, 2], [10, 1, 0], [5, 8, 24]])
np.median(array)
print(np.median(array))

np.mean(array)
print(np.mean(array))

np.std(array)
print(np.std(array))

np.var(array)
print(np.var(array))

# Upto 4 decimal
print(f"Printing all values upto 4 decimal points/n")
print(round(np.median(array), 4))
print(round(np.mean(array), 4))
print(round(np.std(array), 4))
print(round(np.var(array), 4))

#Upto 3 decimal
print(f"Printing all values upto 3 decimal points/n")
print(f"{np.median(array):.3f}")
print(f"{np.mean(array):.3f}")
print(f"{np.std(array):.3f}")
print(f"{np.var(array):.3f}")

4.0
6.333333333333333
6.944222218666553
48.22222222222222
Printing all values upto 4 decimal points/n
4.0
6.3333
6.9442
48.2222
Printing all values upto 3 decimal points/n
4.000
6.333
6.944
48.222


In [48]:
# Element wise concatenation of two arrays of string
x = np.array(["Hello", "World"])
y = np.array(['Welcome', 'Learners'])
results = np.char.add(np.char.add(x, " "), y)
print(results)

['Hello Welcome' 'World Learners']


In [57]:
# Replacing the old substring with the new substring
string = "Hello How Are You"
print(string)
z = np.char.replace(string, "Hello", "Hi")
print(f"After replacing 'Hello' with 'Hi' string becomes : {z}")

Hello How Are You
After replacing 'Hello' with 'Hi' string becomes : Hi How Are You


In [54]:
# Converting all lower case to upper case
str1 = "hello how are you"
print(str1)
z = np.char.upper(str1)
print(f"Converting {str1} into upper case : {z}")

str2 = "GREETINGS OF THE DAY"
print(str2)

s = np.char.lower(str2)
print(f"Converting {str2} into lower case : {s}")

hello how are you
Converting hello how are you into upper case : HELLO HOW ARE YOU
GREETINGS OF THE DAY
Converting GREETINGS OF THE DAY into lower case : greetings of the day
